### ISSUE TITLE
ldas_setup issue

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSldas#757]
On develop branch, when we setup global model experiment ( same as one from nightly tests) with any boundary conditions version ( NLv3 for this experiment) and run with option `RESTART=1` , ldas setup will work and create experiment and run. 
If we do same thing but set `RESTART=2` experiment setup will fail with message: 

linking bcs...
Creating and linking restart...
Traceback (most recent call last):
  File "/gpfsm/dnb55/borescan/brisi/develop/apr_2/GEOSldas/install-SLES15/bin/./ldas_setup", line 1751, in <module>
    status = ld.createLnRstBc()
             ^^^^^^^^^^^^^^^^^^
  File "/gpfsm/dnb55/borescan/brisi/develop/apr_2/GEOSldas/install-SLES15/bin/./ldas_setup", line 862, in createLnRstBc
    config['slurm']['account'] = self.rqdRmInp['account']
    ~~~~~~^^^^^^^^^
  File "/usr/local/other/GEOSpyD/23.5.2-0_py3.11/2023-11-02/lib/python3.11/site-packages/ruamel/yaml/comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'slurm'

**Comment by biljanaorescanin** [comment]
@weiyuan-jiang am I missing something here? Let me know if you can reproduce error?

**Comment by biljanaorescanin** [comment]
In offline communication @weiyuan-jiang noticed global model experiment setup has no input dir and that is needed to extract tile information in case of using restart=2.

**Comment by biljanaorescanin** [comment]
This issue is fixed with: https://github.com/GEOS-ESM/GEOSldas_GridComp/pull/17

**Comment by biljanaorescanin** [comment]
Closing since issue is resolved with merge of PR 17 on GEOSldas_GridComp.
